version: '3.9'

services:

  db:
    image: postgres
    container_name: database
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: default_database

    ports:
      - "5432:5432"